// src/KerrShadow.inl
// Generated by scripts/generate_kerr.py

// Analytical limits for the photon region and Bardeen impact parameters
inline double compute_xi(double r_p, double M, double a) {
    return (std::pow(a, 2)*(M + r_p) + std::pow(r_p, 2)*(-3*M + r_p))/(a*(-M + r_p));
}
inline double compute_eta(double r_p, double M, double a) {
    return std::pow(r_p, 3)*(4*M*std::pow(a, 2) - r_p*std::pow(-3*M + r_p, 2))/(std::pow(a, 2)*std::pow(-M + r_p, 2));
}

