// src/MetricTensor.cpp
#include "RelSpacetime/MetricTensor.h"
#include "RelSpacetime/RelativityTypes.h" 

namespace RelSpacetime {

    double MetricTensor::calculateIntervalSq(const SpacetimeVector& a, const SpacetimeVector& b) const {
        Eigen::Vector4d dx = b.getEigenVector() - a.getEigenVector();
        Eigen::Matrix4d local_g = getMetricAt(a); 
        
        double ds2 = dx.dot(local_g * dx);
        return ds2;
    }

    Eigen::Matrix4d KerrMetric::getMetricAt(const SpacetimeVector& pos) const {
    Eigen::Matrix4d g = Eigen::Matrix4d::Zero();
    
    double M = mass;
    double a = spin;
    double t = pos.t();
    double x = pos.x();
    double y = pos.y();
    double z = pos.z();

    // Include the new file generated by your Python script
    #include "KerrMetric.inl"

    return g;
    }

    std::vector<Eigen::Matrix4d> MetricTensor::getChristoffelSymbols(const SpacetimeVector& pos) const {
        // gamma[mu](alpha, beta)
        std::vector<Eigen::Matrix4d> gamma(4, Eigen::Matrix4d::Zero());
        
        Eigen::Matrix4d g_inv = getInverseMetricAt(pos);
        double h = 1e-5; 
        
        Eigen::Vector4d p = pos.getEigenVector();
        std::vector<Eigen::Matrix4d> dg_dx(4);

        // derivatives of the metric (t, x, y, z)
        for (int i = 0; i < 4; ++i) {
            Eigen::Vector4d p_plus = p;  p_plus[i] += h;
            Eigen::Vector4d p_minus = p; p_minus[i] -= h;

            Eigen::Matrix4d g_plus = getMetricAt(SpacetimeVector(p_plus[0], p_plus[1], p_plus[2], p_plus[3]));
            Eigen::Matrix4d g_minus = getMetricAt(SpacetimeVector(p_minus[0], p_minus[1], p_minus[2], p_minus[3]));
            
            // (f(x+h) - f(x-h)) / 2h
            dg_dx[i] = (g_plus - g_minus) / (2.0 * h); 
        }
    
        // Γ^mu_{alpha, beta} = 1/2 * g^{mu, lambda} * (∂_alpha g_{beta, lambda} + ∂_beta g_{alpha, lambda} - ∂_lambda g_{alpha, beta})
        for (int mu = 0; mu < 4; ++mu) {
            for (int alpha = 0; alpha < 4; ++alpha) {
                for (int beta = 0; beta < 4; ++beta) {
                    
                    double sum = 0.0;
                    for (int lambda = 0; lambda < 4; ++lambda) {
                        sum += g_inv(mu, lambda) * (
                            dg_dx[alpha](beta, lambda) + 
                            dg_dx[beta](alpha, lambda) - 
                            dg_dx[lambda](alpha, beta)
                        );
                    }
                    gamma[mu](alpha, beta) = 0.5 * sum;
                }
            }
        }

        return gamma;
    }

    std::vector<Eigen::Matrix4d> KerrMetric::getChristoffelSymbols(const SpacetimeVector& pos) const {
        std::vector<Eigen::Matrix4d> gamma(4, Eigen::Matrix4d::Zero());
        
        double M = mass;
        double a = spin;
        double t = pos.t();
        double x = pos.x();
        double y = pos.y();
        double z = pos.z();

        if (x*x + y*y + z*z < 1e-14) {
            return gamma; 
        }

        #include "KerrChristoffel.inl"

        return gamma;
    }

    void KerrMetric::getBoyerLindquistCoords(const SpacetimeVector& pos, double& r, double& theta) const {
        double x = pos.x();
        double y = pos.y();
        double z = pos.z();
        
        double R2 = x*x + y*y + z*z;
        double a2 = spin * spin;
        
        // Inverse Kerr-Schild to Boyer-Lindquist r
        double half_term = (R2 - a2) * 0.5;
        double r2 = half_term + std::sqrt(half_term * half_term + a2 * z * z);
        r = std::sqrt(r2);
        
        // Latitude theta
        if (r > 1e-6) {
            theta = std::acos(std::clamp(z / r, -1.0, 1.0));
        } else {
            theta = M_PI / 2.0; // Equatorial fallback
        }
    }

    Eigen::Vector4d MetricTensor::enforceNullCondition(const SpacetimeVector& pos, const Eigen::Vector3d& k_spatial) const {
        Eigen::Matrix4d g_obs = getMetricAt(pos);
        
        double A = g_obs(0, 0); 
        double B = 0.0;         
        double C = 0.0;         
        
        for(int i = 1; i <= 3; ++i) B += 2.0 * g_obs(0, i) * k_spatial(i - 1);
        for(int i = 1; i <= 3; ++i) {
            for(int j = 1; j <= 3; ++j) {
                C += g_obs(i, j) * k_spatial(i - 1) * k_spatial(j - 1);
            }
        }
        
        double discriminant = B * B - 4.0 * A * C;
        double k_time = -1.0; 
        
        if (std::abs(A) <= 1e-12) {
            if (std::abs(B) > 1e-12) {
                k_time = -C / B; 
            }
        } else if (discriminant >= 0.0) {
            double sqrt_disc = std::sqrt(discriminant);
            
            // Lock onto the continuous past-directed branch (-B + sqrt(D)) / 2A.
            // use the stable quadratic formulation to prevent 0/0 precision loss
            if (B > 0.0) {
                k_time = (-2.0 * C) / (B + sqrt_disc); 
            } else {
                k_time = (-B + sqrt_disc) / (2.0 * A);
            }
        }
        
        return Eigen::Vector4d(k_time, k_spatial.x(), k_spatial.y(), k_spatial.z());
    }
    
} // namespace RelSpacetime.

